name: Deploy React App to Google Cloud Run

on:
  push:
    branches:
      - develop # develop 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app:$GITHUB_SHA .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy react-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
